### ISSUE TITLE
installation of clasp fails

### ISSUE THREAD

**Issue by rcemper** [caretdev/iris-analytics-datastudio#1]
1. The demo of Google graphics looks nice.  Though I expected to see some DeepSee dashboard.  
2. Running with FULL administrator rights Installation of clasp returns some WARNings
````
C:\Users\cemper>npm i @google/clasp -g
C:\Users\cemper\AppData\Roaming\npm\clasp -> C:\Users\cemper\AppData\Roaming\npm\node_modules\@google\clasp\build\src\index.js
C:\Users\cemper\AppData\Roaming\npm
`-- @google/clasp@2.4.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\@google\clasp\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
````
3. next clasp login failed massively   
````
C:\Users\cemper>clasp login
C:\Users\cemper\AppData\Roaming\npm\node_modules\@google\clasp\build\src\index.js:2
import why from 'wtfnode'; // should be your first require
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
````
4. I got the strong impression that this package was NEVER tested in a Windows environment.
Elementary prerequisites seem to be missing.

5. I'm somewhat disappointed that against OEX practice this example  was NOT
packaged in a Docker image and left me with a bunch of broken code in my environment.

**Comment by daimor** [comment]
clasp is not my project, it's from Google.

It was not packed with Docker, due to the way, how the code actually executes. And the only thing is working locally is that `clasp` tool, which is in fact just a helper for developer. You can install it manually to your Google Apps Script, you may try to follow the instructions from [here](https://github.com/caretdev/fhir-datastudio#set-up-this-connector-for-personal-use).

As a note about DeepSee dashboard, Google Data Studio in fact quite limited, and from the connector point I can only offer the sources of Data, dimensions and metrics available for it, and return the table by requests from Data Studio. So, I have no way to promote Dashboards from DeepSee or even pivots. My code will generate MDX queries just by requests from Data Studio, and converts the result to expected by Data Studio format.

**Comment by rcemper** [comment]
I know clasp is not yours. I hope you know a hack to make it work. it's JS in the end.

Sorry. I tried in various ways. With not so much success. 
I just got lost.

**Comment by daimor** [comment]
The previous project I did with the web editor, and too many actions with dialogs, and it was pain. Now I found a better way for just for development, and it make my life easier with clasp. Unfortunately, it's not universal, and as we know Windows not so good with nodejs. But I've looked at Dockerization for it, and looks like it may not help, at least with clasp login. 

Google may also have some hidden requirements, which I may miss, if I already configured it.

**Comment by daimor** [comment]
I've found a workaround, how to connect to my deployment
First of all, open this link, to my project in Apps Script
https://script.google.com/d/1xHuWbPXQoy4879vtELDQOtbctzj8ULUuifbtZys4SsKBJRzo6WfxONQ9/edit?usp=sharing

And then, in Data Studio, should be available to use my Deployment ID
AKfycbybyGaRvGfwHZG2DuMrxxoX89zAtYERo25POZNNTS_Lb-GpYRsf4xlpGmV7335nJT37VQ
